### PR TITLE
feat: Add all time zone names

### LINKED ISSUE #14: Nothing seem to happend when clicking on “Other…”
## Issue

I would like to specify a time zone not listed in [the default list](https://github.com/mibus/MultiClock/blob/master/extension.js#L24-L32).

When I click on “Other…”, nothing happens. (Yet when I click on one of the listed time zone, the clock changes as expected.)

## Context

I have installed MultiClock from [Gnome extensions](https://extensions.gnome.org/extension/605/multiclock/), and it installed correctly:

```
cat ~/.local/share/gnome-shell/extensions/MultiClock@mibus.org/metadata.json | grep version
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "A clock for showing a second timezone in the panel.",
  "name": "MultiClock",
  "settings-schema": "org.gnome.shell.extensions.mibusMultiClock",
  "shell-version": [
    "3.36",
    "40.0"
  ],
  "url": "https://github.com/mibus/MultiClock",
  "uuid": "MultiClock@mibus.org",
  "version": 8
}%                                                                    
```

My system runs Fedora 33, GNOME 3.38.5, X11.

### PR DESCRIPTION
**Pull request by l0b0**
This includes all the "canonical" time zone names from
<https://en.wikipedia.org/w/index.php?title=List_of_tz_database_time_zones&oldid=1047681771>
plus UTC.

Unfortunately GNOME doesn't deal with this appropriately, so I'll have to create a sub-menu type thing.

Closes https://github.com/mibus/MultiClock/issues/14.

### CODE REVIEW

**Comment by mibus** [comment]
Yeah, the UI aspect was why I hadn't done anything here. I'd be thrilled to add this, if the submenu idea pans out.

**Comment by l0b0** [comment]
@mibus Do you know how to navigate the documentation? I couldn't find where `Lang.Class.menu.addAction` is documented.

**Comment by mibus** [comment]
I do not. When I was last doing work on the extension, I just downloaded all of the related source code (gnome-shell, I don't remember if there was anything else) and did a lot of grepping.

**Comment by Demetrio92** [comment]
Absolute must-have.

**Comment by l0b0** [comment]
Anyone willing and able to take over this? The code is completely unfamiliar to me.

**Comment by l0b0** [comment]
Project seems to be dead; closing.

**Pull request closed without merging**
